import { Component } from '@angular/core';
import { SharedModule } from '../../../../shared/shared.module';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { SpkWishlistComponent } from '../../../../@spk/reusable-apps/spk-wishlist/spk-wishlist.component';
import { SpkDropdownsComponent } from '../../../../@spk/reusable-ui-elements/spk-dropdowns/spk-dropdowns.component';

@Component({
    selector: 'app-wishlist',
    imports: [SharedModule, NgbModule, RouterModule, CommonModule, SpkWishlistComponent, SpkDropdownsComponent],
    templateUrl: './wishlist.component.html',
    styleUrl: './wishlist.component.scss'
})
export class WishlistComponent {
  products = [
    {
      id: 1,
      name: "CapturePro Camera",
      price: "$120",
      originalPrice: "$399",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/06.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 2,
      name: "Stylish Headset",
      price: "$567",
      originalPrice: "$999",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/12.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 3,
      name: "Altra Pro bearua",
      price: "$2,755",
      originalPrice: "$3,575",
      stockStatus: "Out Of Stock",
      stockStatusClass: "text-danger",
      image: "./assets/images/ecommerce/jpg/05.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 4,
      name: "Alarm Clock",
      price: "$673",
      originalPrice: "$756",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/3.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 5,
      name: "Teddy Bear Toys",
      price: "$1,074",
      originalPrice: "$2,999",
      stockStatus: "Out Of Stock",
      stockStatusClass: "text-danger",
      image: "./assets/images/ecommerce/jpg/15.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 6,
      name: "Cobra Perfume",
      price: "$745",
      originalPrice: "$865",
      stockStatus: "Out Of Stock",
      stockStatusClass: "text-danger",
      image: "./assets/images/ecommerce/jpg/1.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 7,
      name: "Flower Pot",
      price: "$189",
      originalPrice: "$250",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/07.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 8,
      name: "Stylish Ladies Shoe",
      price: "$869",
      originalPrice: "$999",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/9.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 9,
      name: "Jasmin Perfume",
      price: "$659",
      originalPrice: "$879",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/08.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 10,
      name: "HP Laptop",
      price: "$59,753",
      originalPrice: "$79,475",
      stockStatus: "In Stock",
      stockStatusClass: "text-success",
      image: "./assets/images/ecommerce/jpg/17.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 11,
      name: "Adidas Men Shoe",
      price: "$1,255",
      originalPrice: "$1,495",
      stockStatus: "Out Of Stock",
      stockStatusClass: "text-danger",
      image: "./assets/images/ecommerce/jpg/02.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    },
    {
      id: 12,
      name: "Softouch Sofa Set",
      price: "$6,844",
      originalPrice: "$7,476",
      stockStatus: "Out Of Stock",
      stockStatusClass: "text-danger",
      image: "./assets/images/ecommerce/jpg/2.jpg",
      rating: 4,
      cartLink: "/apps/ecommerce/cart",
      productLink: "/apps/ecommerce/product-details",
    }
  ];
}
