import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { SharedModule } from '../../../../shared/shared.module';
import { SpkReusableTablesComponent } from '../../../../@spk/spk-reusable-tables/spk-reusable-tables.component';
import { SpkDropdownsComponent } from '../../../../@spk/reusable-ui-elements/spk-dropdowns/spk-dropdowns.component';

@Component({
    selector: 'app-job-list',
    imports: [SharedModule, NgbModule, RouterModule, SpkReusableTablesComponent, SpkDropdownsComponent],
    templateUrl: './job-list.component.html',
    styleUrl: './job-list.component.scss'
})
export class JobListComponent {
  cartColumn = [
    {header:'Job Title'},
    {header:'Company'},
    {header:'Department'},
    {header:'Applications'},
    {header:'Vacancies'},
    {header:'Status'},
    {header:'Job Type'},
    {header:'Posted Date'},
    {header:'Expires on'},
    {header:'Action'},
  ]
  jobData = [
    {
      id: 'checkboxNoLabeljob22',
      checked: false,
      icon: 'ri-html5-line',
      avatarColor: 'primary',
      title: 'HTML Developer - Fresher',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/8.png',
      companyName: 'Salesforce.Inc',
      department: 'Development',
      applied: 10,
      hired: 15,
      status: 'Approved',
      statusColor: 'primary',
      jobType: 'Full Time',
      startDate: 'Oct 12 2024',
      endDate: 'Nov 12 2024',
      statusIcon: 'bi bi-clock',
     
    },
    {
      id: 'checkboxNoLabeljob33',
      checked: true,
      icon: 'ri-reactjs-line',
      avatarColor: 'secondary',
      title: 'React Lead Developer',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/10.png',
      companyName: 'Hitachi.pvt.Ltd',
      department: 'Design',
      applied: 31,
      hired: 50,
      status: 'Rejected',
      statusColor: 'danger',
      jobType: 'Full Time',
      startDate: 'Nov 07 2024',
      endDate: 'Dec 07 2024',
      statusIcon: 'bi bi-clock',
      
    },
    {
      id: 'checkboxNoLabeljob44',
      checked: true,
      icon: 'ri-vuejs-line',
      avatarColor: 'success',
      title: 'Vuejs Frontend Developer',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/1.png',
      companyName: 'Heineken N.V.',
      department: 'Management',
      applied: 15,
      hired: 35,
      status: 'Pending',
      statusColor: 'warning',
      jobType: 'Part Time',
      startDate: 'Dec 15 2024',
      endDate: 'Jan 15 2025',
      statusIcon: 'bi bi-clock',
      
    },
    {
      id: 'checkboxNoLabeljob55',
      checked: false,
      icon: 'ri-wordpress-line',
      avatarColor: 'info',
      title: 'Wordpress Developer - Remote',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/2.png',
      companyName: 'Siemens AG',
      department: 'Marketing',
      applied: 20,
      hired: 60,
      status: 'Approved',
      statusColor: 'primary',
      jobType: 'Part Time',
      startDate: 'Jan 12 2024',
      endDate: 'Feb 12 2024',
      statusIcon: 'bi bi-clock',
      
    },
    {
      id: 'checkboxNoLabeljob2',
      checked: false,
      icon: 'ri-html5-line',
      avatarColor: 'warning',
      title: 'HTML Developer - Fresher',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/8.png',
      companyName: 'Kellogg Company',
      department: 'Development',
      applied: 10,
      hired: 15,
      status: 'Approved',
      statusColor: 'primary',
      jobType: 'Full Time',
      startDate: 'Oct 12 2024',
      endDate: 'Nov 12 2024',
      statusIcon: 'bi bi-clock',
      
    },
    {
      id: 'checkboxNoLabeljob3',
      checked: true,
      icon: 'ri-reactjs-line',
      avatarColor: 'primary',
      title: 'React Lead Developer',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/10.png',
      companyName: 'Dropbox.Inc',
      department: 'Design',
      applied: 31,
      hired: 50,
      status: 'Rejected',
      statusColor: 'danger',
      jobType: 'Full Time',
      startDate: 'Nov 07 2024',
      endDate: 'Dec 07 2024',
      statusIcon: 'bi bi-clock',
      
    },
    {
      id: 'checkboxNoLabeljob4',
      checked: true,
      icon: 'ri-vuejs-line',
      avatarColor: 'danger',
      title: 'Vuejs Frontend Developer',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/1.png',
      companyName: 'SAP Concur Technologies',
      department: 'Management',
      applied: 15,
      hired: 35,
      status: 'Pending',
      statusColor: 'warning',
      jobType: 'Part Time',
      startDate: 'Dec 15 2024',
      endDate: 'Jan 15 2025',
      statusIcon: 'bi bi-clock',
      
    },
    {
      id: 'checkboxNoLabeljob5',
      checked: false,
      icon: 'ri-wordpress-line',
      avatarColor: 'info',
      title: 'Wordpress Developer - Remote',
      location: 'Remote/Onsite',
      companyLogo: './assets/images/company-logos/2.png',
      companyName: 'TikTok Pte. Ltd',
      department: 'Marketing',
      applied: 20,
      hired: 60,
      status: 'Approved',
      statusColor: 'primary',
      jobType: 'Part Time',
      startDate: 'Jan 12 2024',
      endDate: 'Feb 12 2024',
      statusIcon: 'bi bi-clock',
      
    }
  ];
  
}
