import { Component } from '@angular/core';
import { NgbDropdownModule, NgbNavModule } from '@ng-bootstrap/ng-bootstrap';
import { SpkOrderComponent } from '../../../../@spk/reusable-apps/spk-order/spk-order.component';

@Component({
    selector: 'app-orders',
    imports: [NgbNavModule, NgbDropdownModule, SpkOrderComponent],
    templateUrl: './orders.component.html',
    styleUrl: './orders.component.scss'
})
export class OrdersComponent {
  orders = [
    {
      id: '#139845',
      productName: 'Alta max Camera',
      date: '02/09/2024',
      status: 'Shipped',
      statusClass: 'bg-success-transparent',
      customerName: 'Mayor Kelly',
      productImage: './assets/images/ecommerce/jpg/06.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$1222.0',
    },
    {
      id: '#139846',
      productName: 'Adidas Gent\'s Shoe',
      date: '10/12/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Andrew Garfield',
      productImage: './assets/images/ecommerce/jpg/02.jpg',
      customerImage: './assets/images/faces/15.jpg',
      price: '$299.0',
    },
    {
      id: '#139847',
      productName: 'Yellow Ladies Bag',
      date: '15/05/2024',
      status: 'Shipped',
      statusClass: 'bg-success-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/03.jpg',
      customerImage: './assets/images/faces/8.jpg',
      price: '$512.0',
    },
    {
      id: '#139848',
      productName: 'Altra bearua',
      date: '11/06/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/05.jpg',
      customerImage: './assets/images/faces/11.jpg',
      price: '$1279.0',
    },
    {
      id: '#139849',
      productName: 'Baby Shoe',
      date: '11/06/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Anandh Beary',
      productImage: './assets/images/ecommerce/jpg/16.jpg',
      customerImage: './assets/images/faces/9.jpg',
      price: '$455.0',
    },
    {
      id: '#139850',
      productName: 'Teddy bear Toy',
      date: '16/06/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/15.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$2563.0',
    },
    {
      id: '#139851',
      productName: 'Samsung Head Set',
      date: '05/11/2024',
      status: 'Shipped',
      statusClass: 'bg-success-transparent',
      customerName: 'Jack Miller',
      productImage: './assets/images/ecommerce/jpg/12.jpg',
      customerImage: './assets/images/faces/14.jpg',
      price: '$634.0',
    },
    {
      id: '#139852',
      productName: 'Flower Pot',
      date: '25/04/2024',
      status: 'Shipped',
      statusClass: 'bg-success-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/07.jpg',
      customerImage: './assets/images/faces/9.jpg',
      price: '$145.0',
    },
    {
      id: '#139853',
      productName: 'Gent\'s Sweat Sweater',
      date: '23/09/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Mayor Kelly',
      productImage: './assets/images/ecommerce/jpg/10.jpg',
      customerImage: './assets/images/faces/16.jpg',
      price: '$599.0',
    },
    {
      id: '#139854',
      productName: 'Alarm Clock',
      date: '14/09/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/3.jpg',
      customerImage: './assets/images/faces/12.jpg',
      price: '$325.0',
    },
    {
      id: '#139855',
      productName: 'Josmin Perfume',
      date: '11/06/2024',
      status: 'Shipped',
      statusClass: 'bg-success-transparent',
      customerName: 'Jack Miller',
      productImage: './assets/images/ecommerce/jpg/08.jpg',
      customerImage: './assets/images/faces/12.jpg',
      price: '$779.0',
    },
    {
      id: '#139856',
      productName: 'Ladies Shoe',
      date: '21/07/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/9.jpg',
      customerImage: './assets/images/faces/11.jpg',
      price: '$3289.0',
    },
  ];
  randomOrders2 = [
    {
      id: '#139845',
      productName: 'Alta max Camera',
      date: '02/09/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Mayor Kelly',
      productImage: './assets/images/ecommerce/jpg/06.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$1222.0',
    },
    {
      id: '#139846',
      productName: 'Adidas Gent\'s Shoe',
      date: '10/12/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Andrew Garfield',
      productImage: './assets/images/ecommerce/jpg/02.jpg',
      customerImage: './assets/images/faces/15.jpg',
      price: '$299.0',
    },
    {
      id: '#139847',
      productName: 'Yellow Ladies Bag',
      date: '15/05/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/03.jpg',
      customerImage: './assets/images/faces/8.jpg',
      price: '$512.0',
    },
    {
      id: '#139848',
      productName: 'Altra bearua',
      date: '11/06/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/05.jpg',
      customerImage: './assets/images/faces/11.jpg',
      price: '$1279.0',
    },
    {
      id: '#139849',
      productName: 'Baby Shoe',
      date: '11/06/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Anandh Beary',
      productImage: './assets/images/ecommerce/jpg/16.jpg',
      customerImage: './assets/images/faces/9.jpg',
      price: '$455.0',
    },
    {
      id: '#139850',
      productName: 'Teddy bear Toy',
      date: '16/06/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/15.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$2563.0',
    },
    {
      id: '#139851',
      productName: 'Samsung Head Set',
      date: '05/11/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Jack Miller',
      productImage: './assets/images/ecommerce/jpg/12.jpg',
      customerImage: './assets/images/faces/14.jpg',
      price: '$634.0',
    },
    {
      id: '#139852',
      productName: 'Flower Pot',
      date: '25/04/2024',
      status: 'Pending',
      statusClass: 'bg-warning-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/07.jpg',
      customerImage: './assets/images/faces/9.jpg',
      price: '$145.0',
    },
  ];
  randomOrders3 = [
    {
      id: '#139845',
      productName: 'Alta max Camera',
      date: '02/09/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Mayor Kelly',
      productImage: './assets/images/ecommerce/jpg/06.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$1222.0',
    },
    {
      id: '#139846',
      productName: 'Adidas Gent\'s Shoe',
      date: '10/12/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Andrew Garfield',
      productImage: './assets/images/ecommerce/jpg/02.jpg',
      customerImage: './assets/images/faces/15.jpg',
      price: '$299.0',
    },
    {
      id: '#139847',
      productName: 'Yellow Ladies Bag',
      date: '15/05/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/03.jpg',
      customerImage: './assets/images/faces/8.jpg',
      price: '$512.0',
    },
    {
      id: '#139848',
      productName: 'Altra bearua',
      date: '11/06/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/05.jpg',
      customerImage: './assets/images/faces/11.jpg',
      price: '$1279.0',
    },
    {
      id: '#139849',
      productName: 'Baby Shoe',
      date: '11/06/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Anandh Beary',
      productImage: './assets/images/ecommerce/jpg/16.jpg',
      customerImage: './assets/images/faces/9.jpg',
      price: '$455.0',
    },
    {
      id: '#139850',
      productName: 'Teddy bear Toy',
      date: '16/06/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/15.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$2563.0',
    },
    {
      id: '#139851',
      productName: 'Samsung Head Set',
      date: '05/11/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Jack Miller',
      productImage: './assets/images/ecommerce/jpg/12.jpg',
      customerImage: './assets/images/faces/14.jpg',
      price: '$634.0',
    },
    {
      id: '#139852',
      productName: 'Flower Pot',
      date: '25/04/2024',
      status: 'Cancelled',
      statusClass: 'bg-secondary-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/07.jpg',
      customerImage: './assets/images/faces/9.jpg',
      price: '$145.0',
    },
  ];
  randomOrders4 = [
    {
      id: '#139845',
      productName: 'Alta max Camera',
      date: '02/09/2024',
      status: 'Shipping',
      statusClass: 'bg-success-transparent',
      customerName: 'Mayor Kelly',
      productImage: './assets/images/ecommerce/jpg/06.jpg',
      customerImage: './assets/images/faces/4.jpg',
      price: '$1222.0',
    },
    {
      id: '#139846',
      productName: 'Adidas Gent\'s Shoe',
      date: '10/12/2024',
      status: 'Shipping',
      statusClass: 'bg-success-transparent',
      customerName: 'Andrew Garfield',
      productImage: './assets/images/ecommerce/jpg/02.jpg',
      customerImage: './assets/images/faces/15.jpg',
      price: '$299.0',
    },
    {
      id: '#139847',
      productName: 'Yellow Ladies Bag',
      date: '15/05/2024',
      status: 'Shipping',
      statusClass: 'bg-success-transparent',
      customerName: 'Mirinda Hers',
      productImage: './assets/images/ecommerce/jpg/03.jpg',
      customerImage: './assets/images/faces/8.jpg',
      price: '$512.0',
    },
    {
      id: '#139848',
      productName: 'Altra bearua',
      date: '11/06/2024',
      status: 'Shipping',
      statusClass: 'bg-success-transparent',
      customerName: 'Simon Cowel',
      productImage: './assets/images/ecommerce/jpg/05.jpg',
      customerImage: './assets/images/faces/11.jpg',
      price: '$1279.0',
    },
  
  ];
}
